### ISSUE TITLE
Playbook_to_install_kafka

### ISSUE THREAD

**Issue by srilekhasoma** [srilekhasoma/playbook_kafka_installation#1]

**Comment by srilekhasoma** [comment]
```
- hosts: all
  tasks:
    - name: Update APT package manager repositories cache
      become: true
      apt:
        update_cache: yes
    - name: Install Java using Ansible
      become: yes
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
           - openjdk-8-jdk

    - name: Download kafka binary files
      become: true
      get_url:
        url: https://dlcdn.apache.org/kafka/3.0.0/kafka_2.12-3.0.0.tgz
        dest: /tmp/kafka_2.12-3.0.0.tgz

    - name: Unpack data dump
      unarchive:
        remote_src: yes
        src: https://dlcdn.apache.org/kafka/3.0.0/kafka_2.12-3.0.0.tgz
        dest: /usr/local/
        mode: "0755"
        remote_src: yes
      register: unarchive13


    - name: copying zookeeper.service file with playbook
      become: true
      copy:
        src: /etc/systemd/system/zookeeper.service
        dest: /etc/systemd/system/zookeeper.service
        owner: root
        group: root
        mode: 0644

    - name: copying kafka.service file with playbook
      become: true
      copy:
        src: /etc/systemd/system/kafka.service
        dest: /etc/systemd/system/kafka.service
        owner: root
        group: root
        mode: 0644

    - name: reload systemd
      become: yes
      command: systemctl daemon-reload

    - name: start zookeeper service
      service:
        name: zookeeper
        state: started
        enabled: yes

    - name: start kafka service
      service:
        name: kafka
        state: started
        enabled: yes
```
